FIELDS = [
    ("institution",                  "Institution",                        None),
    ("program_name",                 "Program Name",                       None),
    ("admissions_contact",           "Admissions Contact",                 None),
    ("program_type",                 "Program Type",                       None),
    ("program_focus",                "Program Focus",                      None),
    ("program_focus_details",        "Program Focus in Details",           None),
    ("program_level",                "Program Level",                      None),
    ("credential_awarded",           "Credential Awarded",                 None),
    ("prerequisites",                "Prerequisites",                      None),
    ("num_courses",                  "# Courses",                          None),
    ("courses",                      "Courses",                            None),
    ("notable_courses",              "Notable Courses",                    None),
    ("class_duration",               "Class Duration",                     None),
    ("min_completion_time",          "Min Completion Time",                None),
    ("program_flexibility",          "Program Flexibility",                None),
    ("cost_per_class_short",         "Cost Per Class Short",               None),
    ("cost_per_class_long",          "Cost Per Class Long",                None),
    ("total_cost",                   "Total Cost",                         None),
    ("delivery_mode",                "Delivery Mode",                      None),
    ("in_person_requirement",        "In-Person Requirement (Yes or No)",  None),
    ("enrollment_options",           "Enrollment Options",                 None),
    ("program_managed_by",           "Program Managed By",                 None),
    ("nsa_cae_cd_accredited",        "NSA CAE-CD Accredited?",             None),
    ("cert_prep",                    "Cert Prep",                          None),
    ("stackable",                    "Stackable",                          None),
    ("stackable_details",            "Stackable Details",                  None),
    ("num_fulltime_faculty",         "# of Full-time Faculty",             None),
    ("faculty_details",              "Faculty Details",                    None),
    ("cert_graduation_requirements", "Certificate Graduation Requirements",None),
    ("program_curriculum",           "Program Curriculum",                 None),
    ("scholarships_available",       "Scholarships Available",             None),
    ("finance_options",              "Finance Options",                    None),
]